### ISSUE TITLE
Annotate facebook tracking elements with fence icon

### ISSUE THREAD

**Issue by groovecoder** [mozilla/contain-facebook#258]
See https://mozilla.invisionapp.com/share/WNREP95GJ4V#/screens/356618742

* [x] FB trackers annotated with fence icon
* [ ] On hover, a tooltip is displayed
* [ ] On clicking tracker button, in-context pop-up appears to warn the user
